name: Deploy Web

on: 
  # pull:
  #   branches: [main]
  workflow_dispatch:

jobs:
  Deploy-Web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get

      # Build Web
      - run: flutter build web

      - uses: actions/upload-artifact@v2
        with:
          name: vTablet_client_web
          path: client/build/web
          
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5b730025d7878dcd418287d4e2b66d8e
          projectName: vtablet-app
          directory: client/build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

